### ISSUE TITLE
¿Este proyecto es una versión moderna de LTI-Tool-Provider-Library-PHP?

### ISSUE THREAD

**Issue by xcesaralejandro** [IMSGlobal/lti-1-3-php-library#11]
Cual es la diferencia de este proyecto con el mencionado en el titulo?

https://github.com/IMSGlobal/LTI-Tool-Provider-Library-PHP

**Comment by mumitr0ll** [comment]
Si. La diferencia es en la version de LTI. Esta PHP proyecto aqui es por la version 1.3 - la version mas nueva and el producto de las proceses de IMS Global en el ano pasado. El proyecto en su pregunta describe proceses usar LTI version 1.1 - una version en produccion normal hoy. El futuro de LTI es version 1.3, a pesar de que la conversion de version 1.1 tendra lugar el próximo dos anos (mas or menos). Perdoneme, por favor, mi espanol es dificil con mi teclado ingles y anos sin practicar.

Dereck
IMS Global

**Comment by xcesaralejandro** [comment]
Gracias por la ayuda, tu español se entiende correctamente 👍
