### ISSUE TITLE
Example vs Game Example development 

### ISSUE THREAD

**Issue by mark-ellul** [IMSGlobal/lti-1-3-php-library#12]
Hi @MartinLenord ,

First of all I would like to thank you for this project, it has been immensely useful in creating my platform integration.

I have noticed the changes you have made over the last few days. Specifically the ability to use a json to define platform details. I noticed that you only updated the game_example. I have a couple of questions.

1. Going forward, are you going to focus on the game example? Or will you bring the example up to speed?

2. With respect to the Assignment and Grades Services implementation in the examples. Do they conform to the LTI specification?  i.e. can I start using those examples to code my platform against? 

3. Should I focus on using the game_example instead of the other example?

Thanks and kind regards,

Mark

**Comment by MartinLenord** [comment]
Hi Mark,
The game_example is the better example for testing LTI advantage as it makes use of all the Advantage specifications.

I may remove the simple launch example at some point. The game example is fully certified for full LTI advantage, so you can use it to test a platform against. https://site.imsglobal.org/certifications/turnitin/38021/lti+1.3+php+library+example

**Comment by mark-ellul** [comment]
@MartinLenord thanks for the update. Congratulations on getting certification. I hope to get our platform certified at some point. Do we have to be a IMS Global member to be certified?
