### ISSUE TITLE
Php version requirements?

### ISSUE THREAD

**Issue by gotaholen1** [IMSGlobal/lti-1-3-php-library#14]
What is the minimum php requirements for this library?  PHP 54 does not seem to be enough.  Thanks.

**Comment by mark-ellul** [comment]
@gotaholen1 I was trying on PHP 5+ and couldn't get it working, I had to deploy on a php 7+ environment to get it to work

**Comment by gotaholen1** [comment]
Thanks, I will give that a try today!

**Comment by MartinLenord** [comment]
@gotaholen1 i can't say i've tried with any older versions, what specific issue are you getting when trying 5.4?

**Comment by MartinLenord** [comment]
Let me know if you are still having issues, and i'll re-open

**Comment by oroalej** [comment]
Hi @MartinLenord, can you tell us what's the minimum PHP version for this library?

**Comment by MartinLenord** [comment]
@oroalej I have not tested it on anything below PHP 7.2
