### ISSUE TITLE
Deep Link on game example expects "launch_id" parameter from platform, but the platform never has that information

### ISSUE THREAD

**Issue by mark-ellul** [IMSGlobal/lti-1-3-php-library#15]
Hi Martin,

I am trying to implement the Deep Linking on a platform. From the IMS Global specification it looks like there is no need for a oidc_login, [https://www.imsglobal.org/spec/lti-dl/v2p0#workflow](https://www.imsglobal.org/spec/lti-dl/v2p0#workflow) . As far as I can tell to start the DeepLink process off the platform needs to shape a LtiDeepLinkingRequest message and pass it to the provider.

The Game example's configure.php expects "launch_id" parameter from platform, but the platform never has that information.

Am I missing something or mis-interpreting something in the Deep Link 2.0 Specification?

Do we need a OIDC Login for Deep Links? If so, I still don't see where the Tool passes the launch_id back to the Platform for a Deep Link launch.

Any help would be very much appreciated.

**Comment by mark-ellul** [comment]
Actually I think I see my problem, for a deep link launch, I should still do a oidc_login  then redirect to the game.php in this case with the message type being a LtiDeepLinkingRequest, which then shows a screen to set the difficulty, which then redirects to configure.php which then sends the LtiDeepLinkingResponse message.

Is that correct?

Is this standard behavior? i.e the workflow doesn't for the deep linking doesn't show the oidc_login process.

**Comment by mumitr0ll** [comment]
Hello Mark,
yes I think you have it right. The request for Deep Linking launch follows the same pattern as the standard LTI launch - you have the OIDC dance and then launch to the registered DL URL. I'm not too terribly familiar with the PHP code in this project, but in the Cert suite we have two endpoints. There is an OIDC third-party endpoint (for starting the OIDC parameter dance), and then a DL launch endpoint that should be called to start the Deep Link launch. The DL Response is then returned in the same window/iframe as in this launch call.

Dereck

**Comment by mark-ellul** [comment]
@mumitr0ll Thanks, the specifications can be quite obtuse at times. There are a bunch of missing examples for parameters etc...

**Comment by MartinLenord** [comment]
Yes, you will need to do the whole OIDC login flow for any message launch, both standard and deep linking. If the docs aren't showing this we should update the docs to make it clearer
