### ISSUE TITLE
Should the LtiDeepLinkingResponse be decoded with the tool's public key?

### ISSUE THREAD

**Issue by mark-ellul** [IMSGlobal/lti-1-3-php-library#16]
Hi,

In the documentation, https://www.imsglobal.org/spec/lti-dl/v2p0#deep-linking-response-message it mentions 

> The response message is a JWT payload, signed using the tool private key, as described in the Security Framework specification

I see in the code that it does indeed encode it with the private key.

However when I came to decode the response the only way I could do it and get a correct response was with a urlsafeB64Decode. With the example shown below.

`$jwt = $params["JWT"];`
`$jwt_parts = explode(".", $jwt);`
`json_decode(JWT::urlsafeB64Decode($jwt_parts[1]), true);`

Am I missing something? 
Why don't I need the tool's public key to decode?
How can I confirm that the response from the Tool Provider is actually from the tool provider? Is it only using the deployment_id?

Thanks and Regards

Mark

**Comment by MartinLenord** [comment]
Hi Mark,

The JWTs aren't encrypted, they are just signed. it is up to the party receiving the JWT to validate the signature on it. You need to be able to decide the JWT before checking the signature to work out which client it came from and which public key to use to validate the signature.

**Comment by mark-ellul** [comment]
Hi Martin,

Yes my problem was that the public key I had generated from the private key was not correct.

I have attached the working public key, which you might want to add to the documentation.

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8osiSa75nmqmakwNNocL
A2N2huWM9At/tjSZOFX1r4+PDclSzxhMw+ZcgHH+E/05Ec6Vcfd75i8Z+Bxu4ctb
Yk2FNIvRMN5UgWqxZ5Pf70n8UFxjGqdwhUA7/n5KOFoUd9F6wLKa6Oh3OzE6v9+O
3y6qL40XhZxNrJjCqxSEkLkOK3xJ0J2npuZ59kipDEDZkRTWz3al09wQ0nvAgCc9
6DGH+jCgy0msA0OZQ9SmDE9CCMbDT86ogLugPFCvo5g5zqBBX9Ak3czsuLS6Ni9W
co8ZSxoaCIsPXK0RJpt6Jvbjclqb4imsobifxy5LsAV0l/weNWmU2DpzJsLgeK6V
VwIDAQAB
-----END PUBLIC KEY-----
