### ISSUE TITLE
Deep link Return URL

### ISSUE THREAD

**Issue by RohitAShirsath** [IMSGlobal/lti-1-3-php-library#19]
Hi Martyn,

Can you please explain where are we get deep link return url in any LMS for LTI 1.3?

So we will submit deep link response content to that URL.

**Comment by RohitAShirsath** [comment]
# #

**Comment by viveklm** [comment]
> Hi Martyn,
> 
> Can you please explain where are we get deep link return url in any LMS for LTI 1.3?
> 
> So we will submit deep link response content to that URL.

Hi Rohit,

Always getting error

{"errors":{"jwt":[{"attribute":"jwt","type":"JWT verification failure","message":"JWT verification failure"}]}}

Not able to understand what wrong i am doing here.

**Comment by DreamerIn** [comment]
> > Hi Martyn,
> > Can you please explain where are we get deep link return url in any LMS for LTI 1.3?
> > So we will submit deep link response content to that URL.
> 
> Hi Rohit,
> 
> Always getting error
> 
> {"errors":{"jwt":[{"attribute":"jwt","type":"JWT verification failure","message":"JWT verification failure"}]}}
> 
> Not able to understand what wrong i am doing here.

@viveklm Did you got any solution for this error?
{"errors":{"jwt":[{"attribute":"jwt","type":"JWT verification failure","message":"JWT verification failure"}]}}
I am also getting the same error from canvas while sending deeplinking response
