### ISSUE TITLE
Is there some docs how to use it?

### ISSUE THREAD

**Issue by aduplii** [IMSGlobal/lti-1-3-php-library#2]
Hello, thank you for this example repository with LTI 1.3 specs implementation. By the way, **how to properly use it** :)?
When I call http://localhost:9001/launch.php it tells me that request should be POST, ok, I send the POST method and another var_dump+die message appeared. So somehow (by looking at code) I figured out that it's necessary to send a jwt param with defined structure with POST. When I send POST method with needed params, the script returns "Register" form with some other fields and after submitting this form - success message - "Deployment complete, please relaunch.
deployed to account" appears. So what does it actually means? How it corresponds to LTI 1.3 and its tools consumers and tool providers...
It would be nice if some more details will be provided.

Thanks.

**Comment by jrissler** [comment]
@aduplii we have other resources that are more of reference implementation with those kind of details, this PHP library just implements against that. Are you part of IMS, or is your company part of IMS? (feel free too email me: jrissler@imsglobal.org) - would be happy to get you started

**Comment by edusystemsdev** [comment]
Hi @jrissler I've send you a mail. I'm facing the exact same problem. Could you please help me to sort this out. Our company is a part of IMS and we want to integrate cengage to our web application.

**Comment by jrissler** [comment]
@edusystemsdev Yes will reply a little later today, happy to help get you going.

**Comment by edusystemsdev** [comment]
@jrissler , Hi could you please help me. Its urgent. Thank you.

**Comment by jrissler** [comment]
@edusystemsdev Yep check your inbox :)

**Comment by Rohi145** [comment]
Hi jrissler, Can you please send me the exact documentation to use this library?

**Comment by MartinLenord** [comment]
@Rohi145 there is documentation on how to use the library here https://github.com/IMSGlobal/lti-1-3-php-library/blob/master/README.md if you have a specific question let me know

**Comment by Rohi145** [comment]
Hi Martin...
Thanks for your prompt reply

I have some basic questions:

1.	How will we distinguish the request is deep link request or Basic launch request?
2.     Is it possible to process LTI 1.1 request using LTI 1.3?

**Comment by MartinLenord** [comment]
Hi @Rohi145 

1) in the library you can call the `is_deep_link_launch` method on a `LTI_Message_Launch` object which will tell you if the launch is meant for deep linking.
```
$launch = LTI\LTI_Message_Launch::from_cache($_REQUEST['launch_id'], new Example_Database());
if (!$launch->is_deep_link_launch()) {
    throw new Exception("Must be a deep link!");
}
```
This checks the `https://purl.imsglobal.org/spec/lti/claim/message_type` claim for the value `LtiResourceLinkRequest`

2) No, this library does not support 1.1 launches. 1.3 is also not backwards compatible with 1.1 launches, but there is a migration guide on how to upgrade from LTI 1.1 https://www.imsglobal.org/spec/lti/v1p3/migr

If you've got any more questions, could you create them as a new issue, as this one is closed and i don't want anything getting lost or going unanswered :)

**Comment by viveklm** [comment]
> @jrissler , Hi could you please help me. Its urgent. Thank you.

@edusystemsdev : Hi could you please help me. Its urgent.
