### ISSUE TITLE
Python implementation

### ISSUE THREAD

**Issue by dmitry-viskov** [IMSGlobal/lti-1-3-php-library#22]
hi guys. if you are interested - i've reimplemented this library on Python:

https://pypi.org/project/PyLTI1p3/
https://github.com/dmitry-viskov/pylti1.3

All suggestions/contribution are welcome

**Comment by MartinLenord** [comment]
Nice, always good to have some more 1.3 implementations 👍 i'll pass it on to the group to see if there are any people interested in contributing
