### ISSUE TITLE
The LTI tool isn't responding properly. Please try again or contact your administrator for help

### ISSUE THREAD

**Issue by Rohi145** [IMSGlobal/lti-1-3-php-library#25]
Hi ,

In Blackboard, We will get the following error message:
The LTI tool isn't responding properly. Please try again or contact your administrator for help
 Any Idea, when it comes?

**Comment by viveklm** [comment]
Did you get the resolution for this??

**Comment by viveklm** [comment]
@Rohi145 : Did you get the resolution for this??

**Comment by Rohi145** [comment]
Create new application and registered again.
