### ISSUE TITLE
OIDC

### ISSUE THREAD

**Issue by abertranb** [IMSGlobal/lti-1-3-php-library#3]
Hi @MartinLenord nice job here! I integrated a draft version with WP and it is very nice

There is any plans to integrate with OIDC? I can help

Best regards

**Comment by MartinLenord** [comment]
I will probably be adding the OIDC flow in the next week during the IMS Quarterly, if you are there, then i'll be happy to have someone to work on it with :)

**Comment by MartinLenord** [comment]
The WIP for this is available on the `oidc` branch

**Comment by MartinLenord** [comment]
OIDC is now complete and has been merged into master 
The whole repo has pretty much been rewritten from scratch so that it can be used as a library.
Let me know if there are any other issues you find :)
