### ISSUE TITLE
LTI_Assignments_Grades_Service not returning all line_items

### ISSUE THREAD

**Issue by mwleinad** [IMSGlobal/lti-1-3-php-library#48]
I think this only returns 10 line items by default, and if the context has more than 10 sometimes it doesn't find it

https://github.com/IMSGlobal/lti-1-3-php-library/blob/3a192de99f3783d76caea462b0d04db28569c123/src/lti/LTI_Assignments_Grades_Service.php#L44

Any way to specify the number of items per page that we want/need?

**Comment by MartinLenord** [comment]
It's probably that the platform is paginating the response and this method doesn't currently handle that. Which platform were you encountering this in?

**Comment by mwleinad** [comment]
Canvas.
I was reading that the platform can do that
https://www.imsglobal.org/spec/lti-ags/v2p0#container-request-filters

So I'm guessing this method has to be modified :/
I forked this project so after I figure it out I will post my solution

**Comment by mwleinad** [comment]
So this is what I ended up doing

```
public function find_or_create_lineitem(LtiLineItem $new_line_item, $assignment_id = null) {
        if (!in_array("https://purl.imsglobal.org/spec/lti-ags/scope/lineitem", $this->service_data['scope'])) {
            throw new LtiException('Missing required scope', 1);
        }

        $queryParam = $assignment_id
            ? '?resource_link_id='.$assignment_id
            : '';

        $line_items = $this->service_connector->make_service_request(
            $this->service_data['scope'],
            'GET',
            $this->service_data['lineitems'].$queryParam,
            null,
            null,
            'application/vnd.ims.lis.v2.lineitemcontainer+json'
        );
```

This would scope the query to only the resourceLinkId and that one at least I'm hoping won't contain more than 10 items (I'm calling it $assignment_id)
