### ISSUE TITLE
"Launch must be a POST" 

### ISSUE THREAD

**Issue by edusystemsdev** [IMSGlobal/lti-1-3-php-library#5]
When i open the `index.php`  this output is recieved

"Launch to launch.php to get started"

So i launch `launch.php` but it shows  

"Launch must be a POST" 

I have seen `launcher.php` file with two buttons `Go` and `Go Deep`. And by clicking this will redirect me to `launch.php` with 2 fatal errors.

can any one help me execute this script.

**Comment by jrissler** [comment]
We will discuss this out-of-band. It's less a library issue and more of a general LTI thing.

**Comment by edusystemsdev** [comment]
ok @jrissler

**Comment by edusystemsdev** [comment]
@jrissler hi james , when i try this code i encountered some issue. can i get some support.

**Comment by jrissler** [comment]
@MartinLenord - do we need more instructions here? I'm assuming you would need a platform in RI or elsewhere to actually do the POST launch to launch.php?

**Comment by MartinLenord** [comment]
Yes, the master branch is still a little out of date and may not work (as there was a move to the OIDC which is on another branch) that code still needs cleaning up before pushing it to master.
There is the launcher.php that does a launch to launch.php, but with the recent changes, i'm not sure if that will work.

**Comment by edusystemsdev** [comment]
@jrissler   Hi , For the time being do we have any way to integrate our LMS to cengage. Haven't find any way for cengage integration with LTI. please help me.

**Comment by MartinLenord** [comment]
@claudevervoort may be able to help you there :)
