### ISSUE TITLE
Working with Canvas and multiple registrations

### ISSUE THREAD

**Issue by danielleEriksen** [IMSGlobal/lti-1-3-php-library#60]
We've got a basic launch validation service set up using this library. Works like a breeze locally, until I add a second set of registration credentials for a registration set up in our Canvas staging environment. 

The problem I'm encountering now is that in Canvas, the value for issuer is not unique, every launch via canvas will have 'canvas.instructure.com' as the value for `iss`. I've got the Database interface set up as required in the readme, and am wondering now if there is any way to get access/pass other values that come in on the initial OIDC request, like `client_id`, so in the event of a Canvas launch, I can use that to find the registration instead.

Is this possible or am I missing something really obvious here?

**Comment by kpommerenke** [comment]
We implemented the database interface with the following methods:
public function find_registration($issuer, $clientID = ""){...}
public function find_registration_by_issuer($issuer){           // Left here to implement the Database interface; not used
        return $this->find_registration($issuer);
    }
public function find_deployment2($issuer, $clientID, $deploymentID){...}
public function find_deployment($issuer, $deploymentID){        // Left here to implement the Database interface; not used
        return $this->find_deployment2($issuer, "", $deploymentID);
    }

We then extended the LTI_Message_Launch and LTI_OIDC_Login classes to only call our new methods.

**Comment by danielleEriksen** [comment]
Thanks for the super quick response  and helpful example @kpommerenke.
