### ISSUE TITLE
Caching a launch forever

### ISSUE THREAD

**Issue by kreut** [IMSGlobal/lti-1-3-php-library#61]
Hi,

I *think* I can do this but just to be on the safe side...

I'm using grade pass back with this library and I'm hoping to cache the launch data once per assignment-student.  Assuming that I save the initial jwt_body in my database, can I re-use it each time for subsequent grade pass backs?  As a use case, I could see a need for my app to update a score for the student well after they may have completed the assignment.

**Comment by mumitr0ll** [comment]
How would you not

**Comment by mumitr0ll** [comment]
Apologies, I closed this by mistake. PIBKAC.

Yes, caching this data is critical and you really must do that. One can easily imagine a linked table that keeps the AGS created lineitems that extend the data for this particular user context. But yes, you'd want to hold this data more or less forever and then work with the linked AGS data downstream.

Dereck

**Comment by kreut** [comment]
Thanks!
