### ISSUE TITLE
Is this library a provider library implementation?

### ISSUE THREAD

**Issue by mark-ellul** [IMSGlobal/lti-1-3-php-library#7]
Is this Library a provider based library or does it contain code that consumers can use?

I was hoping to get a library that we can interact with to prepare (JWT encrypt etc) the LTI 1.3 messages to send to a provider. If this library doesn't do that, is there a library we can use to implement the LTI 1.3 as a consumer?

Thanks and Regards,
Mark

**Comment by MartinLenord** [comment]
Hi Mark,

Currently this code focuses around developing tools, we don't have any libraries for dealing with platforms.
Having said that, the Firebase library that is used within this code to sign JWTs for the tool, can also be used to sign platform JWTs, it just doesn't have the LTI specific modelling around it

Thanks,
Martin

**Comment by mark-ellul** [comment]
Hi Martin,

Thanks for responding. So if this is for developing tools, I could use this code to validate my platform code for launching a LTI Link and sending Grades to my platform?

Thanks and Regards

Mark

**Comment by MartinLenord** [comment]
Hi Mark,
Yes, indeed you can!
You can also use the IMS reference implementation to test out your platform https://github.com/IMSGlobal/lti-reference-implementation

**Comment by mark-ellul** [comment]
Hi Martin,

Unfortunately the IMS reference implementation is still closed to the public, at least the code is closed.

If you know of any other LTI 1.3 libraries that are out there I would appreciate it if you let me know, as I have to convince some tool providers to implement LTI 1.3 so any source that can help them would be appreciated.

Thanks and Regards

Mark

Mark

**Comment by jrissler** [comment]
@mark-ellul Reach out to Lisa, she can help you

**Comment by mark-ellul** [comment]
@jrissler  do you know how I can contact Lisa? is it @ LMattson ?

**Comment by MartinLenord** [comment]
Blackboard also have an example LTI tool written in node that i think is open source @ewpreston might be able to point you in the direction of that

**Comment by jrissler** [comment]
@mark-ellul you can reach out to me jrissler@imsglobal.org and I'll put you in touch.

**Comment by mark-ellul** [comment]
Closing out. Thanks to @MartinLenord @jrissler and @LMattson for your help
