### ISSUE TITLE
Platform keys with example code

### ISSUE THREAD

**Issue by mark-ellul** [IMSGlobal/lti-1-3-php-library#8]
Hi,

As discussed in another issue I am trying to implement a platform and use this library as a tool provider for testing.

I know that when I try to trigger the launch.php I need to JWT::encode the message. I see in the example (simple) that there is a jwks.json which is used to decrypt the message. 

What is the private key that matches the jwks.json so that I can encode the message in the format that the example can decode it in?  

Thanks and Regards

Mark

**Comment by mark-ellul** [comment]
PS: Is it the "private.key" in the example folder? Or does the jwks.json public key match a different private key?

**Comment by MartinLenord** [comment]
yes, in the example, both platform and tool configuration use the same keyset

**Comment by mark-ellul** [comment]
Thanks @MartinLenord , closing out the issue

**Comment by mark-ellul** [comment]
@MartinLenord  my apologies for the stupid question, but how did you generate a private key and a matching JWK? 

I have been searching and haven't found a good way to generate a private key and a JWK.

**Comment by MartinLenord** [comment]
You can generate a private and public key by doing:
```
openssl genpkey -algorithm RSA -out rsa_private.pem -pkeyopt rsa_keygen_bits:2048
openssl rsa -in rsa_private.pem -pubout -out rsa_public.pem
```

I'm not aware of a nice way of generating a JWK in php, so it may be worth just putting your **public key** through an online converter then hosting the JWK as a static file.

You would only need to do this once as you can use the same platform key across all tools. You could do it again if you wanted to rotate the key

**Comment by mark-ellul** [comment]
thanks @MartinLenord I knew about the generation of RSA keys just not how to convert to JWK, I will keep on investigating on the way to convert it. Thanks

**Comment by viveklm** [comment]
@mark-ellul : Did you find a solution for this??
